config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :edit, :update, :show]
  resources :posts, only: [:index, :new, :create, :show, :edit, :update] do
    resources :comments, only: :create
    get :search, on: :collection
    namespace :api do
      resources :comments, only: :index, defaults: { format: 'json' }
    end
  end
end
 

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  def show_comment_num
    if comments.present?
      comments.count
    else
      '0'
    end
  end

  def show_last_comment
    if (last_comment = comments.last).present?
      last_comment.text
    else
      ' まだコメントはありません'
    end
  end

  def show_last_comment_date
    if (last_comment = comments.last).present?
      last_comment.created_at.strftime("%Y年%m月%d日 %H:%M")
    else
      ' '
    end
  end

  def show_last_comment_user
    if (last_comment = comments.last).present?
      last_comment.user.name
    else
      ' '
    end
  end

  def show_last_comment_disease
    if (last_comment = comments.last).present?
      last_comment.user.disease
    else
      ' '
    end
  end

  def show_last_comment_history
    if (last_comment = comments.last).present?
      "病歴: #{last_comment.user.history}年"
    else
      ' '
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  
  def index
    @posts = Post.includes(:user).order("updated_at DESC")
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to "/posts#index", notice: '質問をアップロードしました。'
    else
      redirect_to "/posts#index"
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @comment_num = @post.comments.count
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to "/posts/#{@post.id}", notice: '質問を更新しました。'
  end

  def search
    if params[:text].present?
      @posts = Post.where('text LIKE ?', "%#{params[:text]}%")
    else
      @posts = Post.none
    end
  end

  private
  
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text).merge(user_id: current_user.id)
  end

end

app/views/posts/_post.html.erb
<div class="post">
  <div class="post-top">
    <div class="post-user">
      <%= post.created_at.strftime("%Y年%m月%d日 %H:%M")%>  <%= post.user.name %> <%= post.user.disease %> 病歴:<%= post.user.history %>年
    </div>
    <div class="comment-num">
      <i class="fas fa-comment-alt"></i> <%= post.show_comment_num %>
    </div>
  </div>
  <div class="post-content">
    <i class="fas fa-comment"></i> <%= post.text %>
  </div>
  <div class="post-bottom">
    <div class="new-comment">
      最新コメント: <%= post.show_last_comment %>
    </div>
    <div class="comment-user">
      <%= post.show_last_comment_date %>
      <%= post.show_last_comment_user %>
      <%= post.show_last_comment_disease %>
      <%= post.show_last_comment_history %>
    </div>
  </div>
  <%= link_to " ", "/posts/#{post.id}", class: 'post-link' %>
</div>

app/views/posts/edit.html.erb
<%= render partial: "layouts/header" %>
<section class="edit-section">
  <div class="comments-list">
      <div class="main-post">
        <div class="main-post-top">
          <div class="main-post-user">
            <%= @post.created_at.strftime("%Y年%m月%d日 %H:%M")%> 
            <%= @post.user.name %> <%= @post.user.disease %> 病歴:<%= @post.user.history %>年
          </div>
          <% if @post.user.image.present? %>
            <%= image_tag @post.user.image_url, size: '50x50', class: "post-image" %>
          <% else %>
            <i class="fas fa-user-circle"></i>
          <% end %>
        </div>
        <div class="edit-content">
          <%= form_with(model: @post, local: true) do |f| %>
            <%= f.text_area :text, class: 'edit-input', placeholder: "text" , rows: "10" %>
            <%= f.submit "更新", class: 'edit-btn' %>
          <% end %>
        </div>
      </div>
  </div>
</section>
<%= render partial: "layouts/footer" %>

app/views/posts/index.html.erb
<%= render partial: "layouts/header" %>
<section class="section">
  <div class="posts-list">
    <div class="posts-header">
      症状や治療について不安に思うことをきいてみよう<i class="far fa-smile-wink"></i> 質問をクリックしてコメントしよう！
    </div>
    <div class="posts-field">
      <% @posts.each do |post| %>
        <%= render partial: "post", locals: { post: post } %>
      <% end %>
    </div>
    <div class="posts-footer">
      <%= form_with model: Post.new, local: true do |f| %>
        <%= f.text_area :text, class: 'post-input', placeholder: "ききたいことを入力してください" %>
        <%= f.submit "アップロード", class: 'post-btn' %>
      <% end %>
    </div>
  </div>
</section>
<%= render partial: "layouts/footer" %>

app/views/posts/search.html.erb
<%= render partial: "layouts/header" %>
<section class="section">
  <div class="posts-list">
    <div class="posts-header">
      <div class="posts-header__sentence">
        症状や治療について不安に思うことをきいてみよう<i class="far fa-smile-wink"></i> 質問をクリックしてコメントしよう！
      </div>
      <div class="posts-header__search">
        <%= form_with url: search_posts_path, method: :get, local: true do |f| %>
          <%= f.text_field :text, placeholder: "検索する" %>
          <label for="search-btn">
            <i class="fas fa-search"></i>
            <%= f.submit :search, id: "search-btn" %>
          </label>
        <% end %>      
      </div>
    </div>
    <div class="posts-field">
      <% @posts.each do |post| %>
        <%= render partial: "post", locals: { post: post } %>
      <% end %>
    </div>
    <div class="posts-footer">
      <%= form_with model: Post.new, local: true do |f| %>
        <%= f.text_area :text, class: 'post-input', placeholder: "ききたいことを入力してください" %>
        <%= f.submit "アップロード", class: 'post-btn' %>
      <% end %>
    </div>
  </div>
</section>
<%= render partial: "layouts/footer" %>

app/views/posts/show.html.erb
<%= javascript_include_tag 'autoReload' %>
<%= render partial: "layouts/header" %>
<section class="section">
  <div class="comments-list">
    <div class="above-field">
      <div class="main-post" data-post-id="<%= @post.id %>">
        <div class="main-post-top">
          <div class="main-post-user">
            <%= @post.created_at.strftime("%Y年%m月%d日 %H:%M")%> 
            <%= link_to @post.user.name, user_path(@post.user.id), method: :get %> 
            <%= @post.user.disease %> 病歴:<%= @post.user.history %>年
          </div>
          <% if @post.user.image.present? %>
            <%= image_tag @post.user.image_url, size: '50x50', class: "post-image" %>
          <% else %>
            <i class="fas fa-user-circle"></i>
          <% end %>
          <div class="comment-num">
            <% if user_signed_in? && current_user.id == @post.user_id %>
            <%= link_to '編集', edit_post_path(@post.id), method: :get %>
            <% end %>
            <i class="fas fa-comment-alt"></i> <%= @comment_num %>
          </div>
        </div>
        <div class="main-post-content">
          <i class="fas fa-comment"></i> <%= @post.text %> 
        </div>
      </div>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <div class="comment" data-comment-id="<%= comment.id %>">
            <div class="comment-top">
              <div class="comment-user">
                <%= comment.created_at.strftime("%Y年%m月%d日 %H:%M")%> 
                <%= link_to comment.user.name, user_path(comment.user.id), method: :get %>
                <%= comment.user.disease %> 病歴:<%= comment.user.history %>年
              </div>
              <%= image_tag comment.user.image_url, size: '50x50', class: "comment-image" %>
            </div>
            <div class="comment-content">
              <i class="fas fa-comment"></i>  <%= comment.text %>
            </div>
          </div>             
        <% end %>
      <% end %>
    </div>
    <div class="comments-footer">
      <%= form_with model: [@post, @comment], local: true, id: "new_comment" do |f| %>
        <%= f.text_area :text, class: 'comment-input', placeholder: "コメントを入力してください" %>
        <%= f.submit "アップロード", class: 'comment-btn' %>
      <% end %>
    </div>
  </div>
</section>
<%= render partial: "layouts/footer" %>